
'use client';

import {
  Banknote,
  BarChart2,
  Book,
  Briefcase,
  Building,
  CalendarCheck,
  ChevronDown,
  CircleDollarSign,
  Cpu,
  CreditCard,
  DollarSign,
  FileText,
  Globe,
  Home,
  LayoutDashboard,
  ListChecks,
  LogOut,
  Map,
  RefreshCw,
  Settings,
  Shield,
  ShieldCheck,
  Target,
  Users,
  Wand2,
  Grid3x3,
  BellRing,
  Bell,
  PiggyBank,
  TrendingUp,
  BookLock,
  ShieldAlert,
  Scaling,
  BrainCircuit,
  BookCopy,
  Link as LinkIcon,
  Landmark,
  Puzzle,
} from 'lucide-react';

export const navItems = [
  { href: '/dashboard', icon: Home, label: 'Dashboard' },
  { href: '/operations', icon: LayoutDashboard, label: 'Daily Ops' },
  { href: '/operations/heatmap', icon: Grid3x3, label: 'Heatmap' },
  { href: '/operations/alerts', icon: BellRing, label: 'Alerts' },
  { href: '/notifications', icon: Bell, label: 'Notifications' },
  { href: '/businesses', icon: Briefcase, label: 'Businesses' },
  { href: '/employees', icon: Users, label: 'Employees' },
  { href: '/employees/attendance', icon: CalendarCheck, label: 'Attendance' },
  { href: '/employees/tasks', icon: ListChecks, label: 'Tasks' },
  { href: '/employees/departments', icon: Building, label: 'Departments' },
  { href: '/kpis', icon: Target, label: 'KPIs' },
  { href: '/payments', icon: CircleDollarSign, label: 'Payments' },
  { href: '/finance', icon: PiggyBank, label: 'Finance Overview' },
  { href: '/financials/global', icon: Banknote, label: 'Global Financials' },
  { href: '/finance/reports', icon: FileText, label: 'Ad-hoc Reports' },
  { href: '/reports', icon: BookCopy, label: 'Exec. Reports' },
  { href: '/reports/portals', icon: LinkIcon, label: 'Investor Portals' },
  { href: '/currencies', icon: DollarSign, label: 'FX Rates' },
  { href: '/countries', icon: Map, label: 'Countries' },
  { href: '/equity', icon: FileText, label: 'Equity' },
  { href: '/corporate', icon: Landmark, label: 'Corp Actions' },
  { href: '/analytics/businesses', icon: BarChart2, label: 'Business Analytics' },
  { href: '/analytics/forecast', icon: TrendingUp, label: 'Forecasting' },
  { href: '/analytics/domains', icon: Globe, label: 'Domains' },
  { href: '/automation', icon: Wand2, label: 'Automation' },
  { href: '/ai', icon: Cpu, label: 'AI Intelligence' },
  { href: '/ai/simulator', icon: Scaling, label: 'Century Simulator' },
  { href: '/ai/strategy', icon: BrainCircuit, label: 'Strategic Planner' },
  { href: '/sync', icon: RefreshCw, label: 'Sync' },
  { href: '/marketplace', icon: Puzzle, label: 'Marketplace' },
  { href: '/compliance', icon: ShieldCheck, label: 'Compliance' },
  { href: '/compliance/gdpr', icon: BookLock, label: 'GDPR' },
  { href: '/security/audit', icon: Shield, label: 'Audit Logs' },
  { href: '/security/permissions', icon: ShieldAlert, label: 'Permissions' },
  { href: '/docs/api', icon: BookCopy, label: 'API Docs' },
  { href: '/docs/help', icon: Book, label: 'Help Center' },
  { href: '/settings', icon: Settings, label: 'Settings' },
  { href: '/settings/billing', icon: CreditCard, label: 'Billing' },
];
